export enum ERROR {
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
}

export enum QUESTION_TYPE {
  SINGLE = 'SINGLE',
  MULTI = 'MULTI',
  YESNO = 'YESNO',
}

export enum FEATURE_STATUS {
  LAUNCH = 'LAUNCH',
  COMING_SOON = 'COMING_SOON',
}
